# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MageEngine_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  MageEngine_config = release
  Sandbox_config = release

else ifeq ($(config),distribution)
  MageEngine_config = distribution
  Sandbox_config = distribution

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MageEngine Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MageEngine:
ifneq (,$(MageEngine_config))
	@echo "==== Building MageEngine ($(MageEngine_config)) ===="
	@${MAKE} --no-print-directory -C Mage -f Makefile config=$(MageEngine_config)
endif

Sandbox: MageEngine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Mage -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribution"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MageEngine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"